export const notificationText = {
    newMessage: 'newMessage',
    paymentVerification: 'paymentVerification',
    paymentSuccess: 'paymentSuccess',
    payoutSuccess: 'payoutSuccess',
    newChangesForReview: 'newChangesForReview',
    changesHasBeenReviewed: 'changesHasBeenReviewed',
    carrierFound: 'carrierFound',
    recieverFound: 'recieverFound',
    searchingForANewPartner: 'searchingForANewPartner',
    purchaseCompleted: 'purchaseCompleted',
    purchaseReviewed: 'purchaseReviewed',
    newReview: 'newReview',
    dealConfirmedByPartner: 'dealConfirmedByPartner',
};
