export const COMISSIONS = {
    PAYMENT_CP_COMISSION: 0.035,
    PAYMENT_CP_COMISSION_NUMBER: 3.9,
    DUE_PAYOUT_CP_COMISSION: 0.015,
    DUE_PAYPUT_CP_COMISSION_NUMBER: 50,
    DUE_OUR_COMISSION: 0.05,
};
